develop: add part of shbin scripts to apbase for simpler runit scripts in further steps

diff --git a/aprunit/etc/runit/p3 b/aprunit/etc/runit/p3
--- a/aprunit/etc/runit/p3
+++ b/aprunit/etc/runit/p3
@@ -1,7 +1,7 @@
 #!/bin/sh
 set -e
 
-PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+#PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
 exec 2>&1
 
@@ -19,9 +19,10 @@ for _script in /etc/postclr.d/*; do
         echo >&2 "*** Running: ${_script}"
         ${_script}
     else
-		echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
+        echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
     fi
 done
-\rm -f /etc/envvars /etc/runit/stopall
+
+rm -f /etc/envvars /etc/runit/stopall
 echo 'Shutting down the container ... ...'
 test -x /etc/init.d/rc && /etc/init.d/rc ${LAST}
